name: simple_ajax
description: A wrapper around Dart's HttpClient.
version: 0.0.3
author: Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://geekwentfreak.com/

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
#  pointycastle: 0.10.0+1

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
